# theme: jekyll-theme-slate

remote_theme             : "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-GB"
title                    : "evolution-modelling"
title_separator          : "-"
subtitle                 : # " "
name                     : &name "Bill Richards" # &name is a YAML anchor which can be *referenced later
description              : &description "stuff about it goes here."
url                      : https://bill-richards.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/evolution" # the subpath of your site, e.g. "/blog"
repository               : "bill-richards/evolution-modelling"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : true # true, false (default)

theme: jekyll-theme-dinky